project:
  type: book
  output-dir: docs

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "PPLE Introduction to Statistical Analysis: tutorial manual"
  author: "David Fleming"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2026) David Fleming
  repo-url: https://github.com/dvlaming/ISA
  repo-actions: [source]
  chapters:
    - index.qmd
    - t1.qmd
    - t2.qmd
    - t3.qmd
    - t4.qmd
    - t5.qmd
  appendices: 
    - a1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual


